require 'standalone_migrations'
StandaloneMigrations::Tasks.load_tasks

task :watch => [:build_backend, :serve_webpack_hot_reload]

task :build => [:build_backend, :build_frontend]

multitask :serve_webpack_hot_reload => [:serve, :webpack_hot_reload]

task :build_backend do
    sh("cd server && stack build")
end

task :serve do
    sh("cd server && stack exec app")
end

task :webpack_hot_reload do
    sh("cd client && npm run watch")
end

task :build_frontend do
    sh("cd client && npm run build")
end