require 'standalone_migrations'
StandaloneMigrations::Tasks.load_tasks

task :default => [:build_all, :serve]

task :build_all => [:build_backend, :build_frontend]

task :build_backend do
    sh("cd server && stack build")
end

task :build_frontend => [:elm, :fuse]

task :elm => [:elm_api_code_generator, :elm_app_js]

task :elm_api_code_generator do
    mkdir_p "client/elm/Shared/"
    sh("cd server && stack exec code-generator")
end

task :elm_app_js do
    mkdir_p "client/dist/"
    sh("cd client && elm-make elm/Main.elm --output static/app.js")
end

task :fuse do
    sh("cd client && node fuse copy && node fuse")
end


task :serve do
    sh("cd server && stack exec app")
end